<?php

declare(strict_types=1);

namespace Flytachi\Kernel\Src\Stereotype;

use Flytachi\Kernel\Src\Http\Response\ResponseBase;

class ResponseXml extends ResponseBase
{
    public function defaultHeaders(): array
    {
        return ['Content-Type' => 'application/xml'];
    }

    public function getBody(): string
    {
        return parent::constructXml($this->content); // TODO: Change the autogenerated stub
    }
}
